### PR TITLE
Added `sizes`, `height` and `width` `Attributes` to the PictureSource…

### PR DESCRIPTION
**Pull request by majortom64**
…Context.

This brings the PictureSourceContext in line with the standard.

### CODE REVIEW

**Review by JohnSundell — CHANGES_REQUESTED** [review]
Looks great! Now just unit tests needed to get this mergable. Let me know if you want me to help out in any way.

**Comment by JohnSundell** [comment]
@majortom64 can we close this PR, since these changes are also included in #91? Would make sense to review and merge them all as one change, I think. Then you could implement the unit tests for all new APIs within that PR, if you'd like.

**Comment by majortom64** [comment]
Trying to steal the glory of a PR from me?!? :-) I am pretty sure I did them as two because they were not part of the component (as they were used by the node), and it meant that they could be added separately.

I am happy to have them all be part of the same PR, but if I have to do something on my end, I need instructions (git/GitHub) are still fairly new to me.

**Comment by JohnSundell** [comment]
@majortom64 No action needed from your side. I'll simply close this PR, and then you'll just push all of your future commits onto your other PR (#91). That is, the `PictureComponent` branch. No rush from my side, I typically only have time once or twice per week to do open source work, but once you've updated your PR to address the comments and added tests, I'll re-review and hopefully get it merged soon 🙂

**Pull request closed without merging**
